### ISSUE TITLE
Not Scrollable on Safari with IOS

### ISSUE THREAD

**Issue by jordisantamaria** [jacobp100/react-twentytwenty#10]
Hi, I tried to play with the props of minDistanceToBeginInteraction and maxAngleToBeginInteraction for allow scroll on mobile, but it's not working for safari with IOS, so users aren't allow to scroll the screen if the image have a big size.

**Comment by jacobp100** [comment]
This definitely sounds like a bug!

The only event we call `preventDefault` is `onTouchStart` (on mobile). [Here's the code for that.](https://github.com/jacobp100/react-twentytwenty/blob/5575ee4b2d6ab44fcc7c300057ef91eb74f9d662/src/index.js#L74) I _think_ this is the issue.

We don't want the page to scroll when they're interacting with the component. I think we're able to stop scrolling by calling `e.preventDefault` in `onTouchMove`. If that's true, we could use `this.state.isDragging` to determine which events we should block.

I made a super quick [PR](https://github.com/jacobp100/react-twentytwenty/pull/11). Could you test to see if that solves the issue?

**Comment by jordisantamaria** [comment]
Hi, I tried the PR and now it works perfect thanks,
It's the first time I test a PR so I was so confuse what to do, that's why I answer so late.

**Comment by jordisantamaria** [comment]
Can you please, update the build version? it's not updated if i install it with npm.

**Comment by jacobp100** [comment]
Sorry for the delay. v1.2.0 is published
