### ISSUE TITLE
Twenty is firing click event when drag ends

### ISSUE THREAD

**Issue by jordisantamaria** [jacobp100/react-twentytwenty#16]
Hi, our team wanted to link to a new page when click an element with twentytwenty and we had the problem, the click event was firing when dragging.

We solve the problem adding the prop onDragEnd on the source code: 

```
public endDrag(e?: any) {
    if (e) {
      e.preventDefault();
      e.stopPropagation();
    }
    document.removeEventListener('mousemove', this.onDragMove);
    document.removeEventListener('mouseup', this.endDrag);
    document.removeEventListener('touchmove', this.onDragMove);
    document.removeEventListener('touchend', this.endDrag);
    **if (this.props.onDragEnd) {
      this.props.onDragEnd();
    }**

    this.setState({ isDragging: false, startY: NaN, endY: NaN });
  }
```

It gives us the control of know when user is draging, so we can do a controlled click like this:

```
public handleDragEnd = () => {
    setTimeout( () => {
      this.setState(() => ({
        dragging: false,
      }));
      this.props.getDragging(false);
    }, 200);
  }
```
I could do a pull request for add it.

**Comment by jacobp100** [comment]
Happy for this to be added - I think we should add a `onDragStart` too for consistency. Are you able to submit a PR? Otherwise I'll try and get to it when I have some free time
