### ISSUE TITLE
Separator does not occur

### ISSUE THREAD

**Issue by mghazanfar** [jacobp100/react-twentytwenty#3]
Hey, I am really obliged to your contribution of this Zurb's twenty-twenty plugin but I do not see the separator between the two images. How to show that and also how to customize that? Please help me ASAO.

**Comment by jacobp100** [comment]
There’s a section in the docs

> You can include a third child to be a slider. The slider is placed inside a zero-width, full height element, positioned to the correct left offset: basically just set height: 100% on your slider

It’s sort of BYOB slider element, so you can customise it however you want. Let me know if you have any further issues!

**Comment by mghazanfar** [comment]
Thanks alot.
