### ISSUE TITLE
Why does the container have overflow: hidden?

### ISSUE THREAD

**Issue by vjustov** [jacobp100/react-twentytwenty#7]
this one in particular: https://github.com/jacobp100/react-twentytwenty/blob/gh-pages/src/index.js#L113

With that style I cannot make the divider taller than the images.

**Comment by jacobp100** [comment]
Add vertical margin or padding to the images to increase the container size, then your divider will be taller

**Comment by jacobp100** [comment]
Did this solve your issue?

**Comment by vjustov** [comment]
No, I haven't tried it, just saw these comments. but it sounds like it would work. But I can't help but wonderwhy do you need it, in my particular use case the component behaved exactly the same without it.

I will check later tonight, when i arrive home

**Comment by jacobp100** [comment]
There are container boxes that stick out of the main component, which would make the main container twice as wide. This would usually cause a horizontal scrollbar to be added to the page when there was not one before. The fix was `overflow: hidden`.
