### ISSUE TITLE
using left/right syntax + updating position of slider

### ISSUE THREAD

**Issue by garris** [jacobp100/react-twentytwenty#9]
I am not sure how I get this to work.  I want VARIABLE_HERE to be rendered.  I also need to know how to update the position of the slider externally.

Can you provide some samples?   thank you.

```
  <TwentyTwenty
    verticalAlign="bottom"
    minDistanceToBeginInteraction={0}
    maxAngleToBeginInteraction={Infinity}
    left={<img alt="cat-1" src=<VARIABLE_HERE> width="200" />}
    right={<img alt="cat-2" src=<VARIABLE_HERE> width="300" />}
    slider={<div className="slider" />}
  />


```

**Comment by jacobp100** [comment]
> I want VARIABLE_HERE to be rendered

Is that part working?

> I also need to know how to update the position of the slider externally.

You can use `position={x}` to set the position to `x`. and then use `onChange` to handle slider position changes from the user.

**Comment by garris** [comment]
I was not able to get the `src=VARIABLE` to work inline (where VARIABLE would equal some valid URL image resource string).    Would be nice to see how to dynamically add images there.

also, your homepage demo does not seem to be working.

**Comment by jacobp100** [comment]
You can add variables the same as in regular React.

```jsx
  <TwentyTwenty
    verticalAlign="bottom"
    left={<img alt="cat-1" src={variable1} width="200" />}
    right={<img alt="cat-2" src={variable2} width="300" />}
    slider={<div className="slider" />}
  />
```
Does http://jacobp100.github.io/react-twentytwenty/ not work for you?

You want to follow something like this:

https://github.com/jacobp100/react-twentytwenty/blob/5575ee4b2d6ab44fcc7c300057ef91eb74f9d662/demo/index.js#L16-L50

**Comment by garris** [comment]
Thank you — I see it now.
